# Generated by Django 3.2 on 2021-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_hero', models.ImageField(blank=True, upload_to='img\\products')),
                ('text_title', models.CharField(max_length=100)),
                ('text_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
