# Generated by Django 3.1 on 2021-05-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210507_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_hero',
        ),
        migrations.RemoveField(
            model_name='product',
            name='text_desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='text_title',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='test', max_length=100, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='test', max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='hero',
            field=models.ImageField(blank=True, upload_to='img\\products', verbose_name='Фото товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='test1', max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
