# Generated by Django 3.1 on 2021-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210518_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgs',
            field=models.ImageField(blank=True, upload_to='img\\products', verbose_name='Фотографии товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero',
            field=models.ImageField(blank=True, upload_to='img\\products', verbose_name='Лицо товара'),
        ),
    ]
