# Generated by Django 3.1 on 2021-05-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210518_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imgs',
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img\\products', verbose_name='Фотографии товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='main.product')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('product',),
            },
        ),
    ]
