# Generated by Django 3.2.4 on 2021-07-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart_app', '0005_remove_shoppingcart_quantity'),
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingCart_app.shoppingcart', verbose_name='продукт'),
        ),
    ]
