# Generated by Django 3.2.4 on 2021-07-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart_app', '0005_remove_shoppingcart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во'),
        ),
    ]
