# Generated by Django 3.1 on 2021-05-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20210507_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='img\\users\\avatars', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.CharField(max_length=400, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=250, verbose_name='ФИО'),
        ),
    ]
