# Generated by Django 3.2.4 on 2021-07-09 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_auto_20210708_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 5, 58, 57, 823439, tzinfo=utc)),
        ),
    ]
